name: MSBuild

on:
  pull_request:
    types: [opened, edited, reopened]
  pull_request_review_comment:
    types: [edited]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: PullRequest Type
        run: write-host "PullRequest Type"
        shell: pwsh
